---
title: "Bienvenue sur notre site"
format: html
editor: visual
---

------------------------------------------------------------------------

## Présentation du projet

Notre objectif est d'explorer des questions fascinantes telles que : Les entreprises les plus innovantes paient-elles les meilleurs salaires ? Demandent-elles davantage de data scientists ou de compétences en machine learning ? Quels secteurs montrent les plus grandes tendances en termes d'innovation et de recrutement ?

------------------------------------------------------------------------

## Objectifs du projet

-   **Analyser les données** : Identifier des tendances et des patterns cachés dans les bases de données.
-   **Visualisation intuitive** : Offrir des graphiques et des visualisations interactives pour rendre les résultats accessibles.

------------------------------------------------------------------------

## Naviguez sur le site

Explorez nos analyses et résultats via les sections ci-dessous :

-   [**Statistiques Descriptives**](Statistiques%20descriptives.qmd)\
    Découvrez une analyse détaillée des bases de données, avec des statistiques sur les brevets, les offres d’emploi et leur appariement.

-   [**Analyse des données**](Analyses%20de%20données.qmd)\
    Explorez les relations entre innovation et demande de compétences grâce à des visualisations créatives, des graphiques et des word clouds.

------------------------------------------------------------------------

## Technologies utilisées

Ce projet utilise des technologies modernes pour garantir la précision et la clarté de nos analyses :

-   **R & Quarto** : Analyse et visualisation des données.
-   **ggplot2 & wordcloud2** : Création de graphiques et visualisations.
-   **GitHub Pages** : Hébergement et déploiement du site.

------------------------------------------------------------------------

## Contactez-nous

Pour toute question ou suggestion, n’hésitez pas à nous contacter. Nous sommes ouverts aux collaborations et aux discussions !

-   [MOIELWAY NGARTI Israël](mailto:israel.moielway-ngarti@u-bordeaux.fr)
-   [BARKIRE DOURAMANE MOUSSA](mailto:barkire.douramane-moussa@u-bordeaux.fr)
-   [FABARIKA TIEBELE KARAMA](mailto:fabarika-tiebele.karama@u-bordeaux.fr)
-   [ISMAÏL ZAROQ](mailto:ismail.zaroq@u-bordeaux.fr)

Bonnes explorations sur notre site !
